apps/front/models.py
# -*- coding: UTF-8 -*-

from exts import db
import shortuuid
from werkzeug.security import generate_password_hash, check_password_hash
import enum
from datetime import datetime


class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UNKNOWN = 4


class FrontUser(db.Model):
    __tablename__ = 'front_user'
    id = db.Column(db.String(50), primary_key=True, default=shortuuid.uuid)
    telephone = db.Column(db.String(30), nullable=False, unique=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(200), nullable=False)
    email = db.Column(db.String(50), nullable=True, unique=True)
    realname = db.Column(db.String(50), nullable=True, unique=True)
    # 头像
    avatar = db.Column(db.String(100), nullable=True, unique=True)
    # 签名
    signature = db.Column(db.String(100), nullable=True, unique=True)
    gender = db.Column(db.Enum(GenderEnum), default=GenderEnum.UNKNOWN)
    join_time = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, *args, **kwargs):
        if 'password' in kwargs:
            self.password = kwargs.get('password')
            kwargs.pop('password')
        super(FrontUser,self).__init__(*args, **kwargs)

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, newpwd):
        self._password = generate_password_hash(newpwd)

    def check_password(self, rawpwd):
        return check_password_hash(self._password, rawpwd)

apps/front/forms.py
# -*- coding: UTF-8 -*-

from ..forms import BaseForm
from wtforms import StringField, ValidationError, IntegerField
from wtforms.validators import Regexp, Email, EqualTo, InputRequired
from utils import lyccache


class SignupForm(BaseForm):
    telephone = StringField(validators=[Email(message='请输入正确的邮箱')])
    # sms_captcha = StringField(validators=[Regexp(r'\w{6}', message='请输入正确格式的验证码')])
    sms_captcha = StringField(validators=[InputRequired(message='请输入正确格式的验证码')])
    # sms_captcha = StringField(validators=[Regexp(r"\w{4}",message='请输入正确格式的短信验证码！')])
    username = StringField(validators=[Regexp(r".{2,20}", message='请输入正确格式的用户名')])
    password1 = StringField(validators=[Regexp(r'[0-9a-zA-Z_\.]{6,20}', message='请输入正确格式的密码')])
    # password1 = StringField(validators=[InputRequired(message='请输入正确格式的密码')])
    password2 = StringField(validators=[EqualTo('password1', message='两次输入的密码不一致')])
    graph_captcha = StringField(validators=[Regexp(r'\w{4}', message='请输入正确格式图形验证码')])

    def validate_sms_captcha(self, field):
        smscaptcha = field.data
        telephone = self.telephone.data
        smscaptcha_mem = lyccache.get(telephone)
        print('smscaptcha_mem is %s' % smscaptcha_mem)
        if not smscaptcha_mem or smscaptcha_mem.lower() != smscaptcha.lower():
            raise ValidationError(message='短信验证码验证错误')

    def validate_graph_captcha(self, field):
        graph_captcha = field.data
        graph_captcha_mem = lyccache.get(graph_captcha.lower())
        if not graph_captcha_mem:
            raise ValidationError(message='图形验证码错误')


class SignInForm(BaseForm):
    telephone = StringField(validators=[Email(message='请输入正确的邮箱')])
    password = StringField(validators=[Regexp(r'[0-9a-zA-Z_\.]{6,20}', message='请输入正确格式的密码')])
    remember = StringField()


class AddPostForm(BaseForm):
    title = StringField(validators=[InputRequired(message='请输入标题')])
    content = StringField(validators=[InputRequired(message='请输入内容')])
    board_id = IntegerField(validators=[InputRequired(message='请输入板块ID')])


class AddCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message='请输入内容')])
    post_id = IntegerField(validators=[InputRequired(message='请输入帖子ID')])

apps/common/views.py
# -*- coding: UTF-8 -*-

from flask import Blueprint, request, make_response, jsonify
from utils import restful, lyccache
import string
import random
import qiniu
from flask_mail import Message
from exts import mail
from ..common.forms import EmailForm
from utils.captcha import Captcha
from io import BytesIO


bp = Blueprint('common', __name__, url_prefix='/common')


@bp.route('/uptoken/', methods=['GET', 'POST'])
def uptoken():
    ak = 'NRZ2Haj_cLFZ8jQLwGibPjx2MmlUppRonEOB9hZR'
    sk = '8AkbHHu048eDLLgwLQRTMACl5wnRhv859UUDOhMC'
    q = qiniu.Auth(access_key=ak, secret_key=sk)
    bucket = 'flask-new'
    # print(qiniu.getUploadUrl())
    token = q.upload_token(bucket)
    print(token)
    return jsonify({'uptoken': token})


# 图形验证码
@bp.route('/captcha/')
def graph_captcha():
    text, image = Captcha.gene_graph_captcha()
    lyccache.set(text.lower(), text.lower())
    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    return resp


@bp.route('/')
def index():
    return 'common index'


@bp.route('/email_captcha/', methods=['POST'])
def email_captcha():
    # email
    # timestamp
    # md5(email + timestamp + salt)
    form = EmailForm(request.form)
    if form.validate():
        email = form.email.data
        source = list(string.ascii_letters)
        # source.extend(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'])
        source.extend(map(lambda x: str(x), range(0, 10)))
        # 随机采样
        captcha = "".join(random.sample(source, 6))
        # 发送验证码
        print('发送了短信验证码: %s' % captcha)
        message = Message(subject='验证码', recipients=[email], body='您的验证码是%s' % captcha)
        try:
            mail.send(message)
        except:
            return restful.servererror()
        lyccache.set(email, captcha)
        return restful.success(message='邮件发送成功')
    else:
        return restful.paramerror(message='参数错误')

# @bp.route('/email_captcha/')
# def email_captcha():
#     # 通过查询字符串的方式将邮箱传递进去
#     # /email_captcha/?email=xxx@qq.com
#     email = request.args.get('email')
#     print(email)
#     if not email:
#         return restful.paramerror('请传递邮箱参数!')
#     # 生成验证码
#     source = list(string.ascii_letters)
#     # source.extend(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'])
#     source.extend(map(lambda x: str(x), range(0, 10)))
#     # 随机采样
#     captcha = "".join(random.sample(source, 6))
#     # 发送验证码
#     message = Message(subject='验证码', recipients=[email], body='您的验证码是%s' % captcha)
#     try:
#         mail.send(message)
#     except:
#         return restful.servererror()
#     lyccache.set(email, captcha)
#     return restful.success(message='邮件发送成功')

apps/front/__init__.py
# -*- coding: UTF-8 -*-

from .views import bp
from . import hooks

apps/front/views.py
# -*- coding: UTF-8 -*-

from flask import Blueprint, views, render_template,\
    redirect, make_response, request, session, url_for, g, abort
from utils.captcha import Captcha
from utils import restful, safeutils
from io import BytesIO
from .models import FrontUser
from .forms import SignupForm, SignInForm, AddPostForm, AddCommentForm
from exts import db
from ..models import BannerModel, BorderModel, PostModel, CommentModel
import config
from .decorates import login_required
from flask_paginate import Pagination, get_page_parameter


bp = Blueprint('front', __name__)


@bp.route('/acomment', methods=['GET', 'POST'])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return restful.paramerror(message='没有这篇帖子')
    else:
        return restful.paramerror(form.get_error())


@bp.route('/p/<post_id>')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html', post=post)


@bp.route('/apost/', methods=['GET', 'POST'])
@login_required
def add_post():
    if request.method == 'GET':
        boards = BorderModel.query.all()
        return render_template('front/front_apost.html', boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BorderModel.query.get(board_id)
            if not board:
                return restful.paramerror(message='没找到该板块')
            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.paramerror(message=form.get_error())


@bp.route('/', strict_slashes=False)
def index():
    board_id = request.args.get('bd', type=int, default=None)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    print(type(page))
    print(page)

    banners = BannerModel.query.order_by(BannerModel.priority).limit(4)
    # banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)
    boards = BorderModel.query.all()
    start = (page-1) * config.PER_PAGE
    end = start + config.PER_PAGE
    # ports = None
    # total = 0
    if board_id:
        total = PostModel.query.filter_by(board_id=board_id).slice(start, end).count()
        posts = PostModel.query.filter_by(board_id=board_id).slice(start, end)
    else:
        posts = PostModel.query.slice(start, end)
        total = PostModel.query.count()
    pagination = Pagination(bs_version=3, page=page, total=total,
                            outer_window=1, inner_window=2)
    context = {
        'banners': banners,
        'boards': boards,
        'posts': posts,
        'pagination': pagination,
        'current_board': board_id
    }
    return render_template('front/front_index.html', **context)


@bp.route('/test/', strict_slashes=False)
def test():
    return render_template('front/test.html')


class SingInView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != url_for('front.signup') and\
                safeutils.is_safe_url(return_to) and return_to != request.url:
            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')

    def post(self):
        form = SignInForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remember.data
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.paramerror(message='手机号码或者密码错误')
        else:
            return restful.paramerror(message=form.get_error())


class SginupView(views.MethodView):
    def get(self):
        # 获取上个页面的url
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signup.html', return_to=return_to)
        else:
            return render_template('front/front_signup.html')

    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password2.data
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success(message='注册成功')
        else:
            print(form.get_error())
            return restful.paramerror(message=form.get_error())


bp.add_url_rule('/signup/', view_func=SginupView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SingInView.as_view('signin'))

templates/front/front_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404</title>
</head>
<body>
您要找的页面到🔥星了
<br>
<br>
<br>
<br>
<br>
<br>
<a href="/">回到首页</a>
</body>
</html>

templates/front/front_apost.html
{% extends "front/front_base_new.html" %}
{% from "common/_macros.html" import static %}

{% block title %}
 发布帖子
{% endblock %}

{% block head %}
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.js') }}"></script>
    <script src="{{ static("front/js/front_apost.js") }}"></script>
{% endblock %}

{% block body %}
<form action="" method="post">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">标题</span>
            <input type="text" class="form-control" name="title">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">板块</span>
            <select name="board_id" class="form-control">
                {% for board in boards %}
                    <option value="{{ board.id }}">{{ board.name }}</option>
                {% endfor %}

            </select>
        </div>
    </div>
    <div class="form-group">
        <script id="editor" type="text/plain" style="height:300px;"></script>
    </div>
    <div class="form-group">
        <button class="btn btn-danger" id="submit-btn">发布帖子</button>
    </div>
</form>
{% endblock %}

templates/front/front_apost_test.html
{% extends "front/front_base_new.html" %}
{% from "common/_macros.html" import static %}

{% block title %}
 发布帖子
{% endblock %}

{% block head %}
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>
    <script src="{{ static("front/js/front_apost.js") }}"></script>
{% endblock %}

{% block body %}
        <script id="editor" type="text/plain" style="height:500px;"></script>

{% endblock %}

templates/front/front_base.html
{% from 'common/_macros.html' import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>
    {% block title %}
    {% endblock %}
    </title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{{ static("common/zlajax.js") }}"></script>
    <link rel="stylesheet" href="{{ static("common/sweetalert/sweetalert.css") }}">
    <script src="{{ static("common/sweetalert/sweetalert.min.js") }}"></script>
    <script src="{{ static("common/sweetalert/zlalert.js") }}"></script>
    <script src="{{ static('common/zlparam.js') }}"></script>
    <link rel="stylesheet" href="{{ static('front/css/front_sign_base.css') }}">

{#    <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>#}
    <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.js"></script>
    {% block head %}
    
    {% endblock %}
</head>
<body>
    <div class="outer-box">
        <div class="logo-box">
            <a href="/">
                <img src="{{ static('common/images/logo.png') }}" alt="">
            </a>
        </div>
        <h2 class="page-title">
            {% block h2_block %}
            
            {% endblock %}
        </h2>
        <div class="sign-box">
            {% block sign_box %}
            
            {% endblock %}
        <span style="display: none" id="return_to_span">{{ return_to }}</span>

    </div>
    </div>
</body>
</html>

templates/front/front_base_new.html
{% from 'common/_macros.html' import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="{{ static("common/zlajax.js") }}"></script>
    <link rel="stylesheet" href="{{ static('front/css/front_base.css') }}">
    <title>
        {% block title %}
        
        {% endblock %}
    </title>
    {% include 'common/_heads.html' %}
    {% block head %}
    
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">python论坛</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">首页 <span class="sr-only">(current)</span></a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="请输入关键字">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
          {% if g.front_user %}
            <span id="login-tag" data-is-login="1" style="display: none"></span>
            <li class="dropdown">
              <a class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                {{ g.front_user.username }}
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="#">个人中心</a></li>
                <li><a href="#">设置</a></li>
                <li><a href="#">注销</a></li>
{#                <li role="separator" class="divider"></li>#}
{#                <li><a href="#">Separated link</a></li>#}
              </ul>
            </li>
        {% else %}
        <li><a href={{ url_for('front.signin') }}>登录</a></li>
        <li><a href={{ url_for('front.signup') }}>注册</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="main-container">
  {% block body %}

{% endblock %}

</div>

</body>
</html>

templates/front/front_index.html
{% extends 'front/front_base_new.html' %}

{% block title %}
python 论坛
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename = 'front/css/front_index.css') }}">
{% endblock %}

{% block body %}
<div class="lg-container">
<div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
  <!-- 指示器 -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
  </ol>

  <!-- 轮播图 -->
   <div class="carousel-inner" role="listbox">
   {% for banner in banners %}
   {% if loop.first %}
   <div class="item active">
        <a href={{ banner.link_url }}>
          <img src={{ banner.image_url }} alt="...">
        </a>
    </div>
   {% else %}
     <div class="item">
        <a href={{ banner.link_url }}>
          <img src={{ banner.image_url }} alt="...">
        </a>
    </div>
   {% endif %}
   {% endfor %}
  </div>

  <!-- 左右切换的控制按钮 -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="post-group">
      <ul class="post-group-head">
          <li class="active"><a href="">最新</a></li>
          <li><a href="">精华帖子</a></li>
          <li><a href="">点赞最多</a></li>
          <li><a href="">评论最多</a></li>
      </ul>
    <ul class="post-list-group">
        {% for post in posts %}
            <li>
            <div class="author-avatar-group">
                <img src="{{ post.author.avatar or url_for('static', filename='common/images/logo.png')}}" alt="">
            </div>
                <div class="post-info-group">
                    <p class="post-title">
                        <a href="{{ url_for('front.post_detail', post_id=post.id) }}">{{ post.title }}</a>
                        </p>
                    <p class="post-info">
                        <span>作者: {{ post.author.username }}</span>
                        <span>发表时间: {{ post.create_time }}</span>
                        <span>评论:0</span>
                        <span>阅读:0</span>
                    </p>
                </div>
            </li>
        {% endfor %}
    </ul>
    <div style="text-align: center">
        {{ pagination.links }}
    </div>

</div>
</div>
<div class="sm-container">
    <div style="padding-bottom: 10px">
        <a href="{{ url_for('front.add_post') }}" class="btn btn-warning btn-block" >发布帖子</a>
    </div>
    <div class="list-group">
        {% if current_board %}
                <a href="/" class="list-group-item">所有板块</a>
        {% else %}
                <a href="/" class="list-group-item active">所有板块</a>
        {% endif %}
        {% for board in boards %}
            {% if board.id == current_board %}
            <a href="{{ url_for('front.index', bd=board.id) }}" class="list-group-item active">{{ board.name }}</a>
            {% else %}
            <a href="{{ url_for('front.index', bd=board.id) }}" class="list-group-item">{{ board.name }}</a>
            {% endif %}
        {% endfor %}

    </div>
</div>
{% endblock %}

templates/front/front_pdetail.html
{% extends 'front/front_base_new.html' %}
{% from 'common/_macros.html' import static %}
{% block title %}
{{ post.title }}
{% endblock %}


{% block head %}
    <link rel="stylesheet" href="{{ static('front/css/front_pdetail.css') }}">
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.js') }}"></script>
    <script src="{{ static("front/js/front_detail.js") }}"></script>
{% endblock %}

{% block body %}
    <div class="lg-container">
        <div class="post-container">
            <h2>{{ post.title }}</h2>
            <p class="post-info-group">
                <span>发表时间: {{ post.create_time }}</span>
                <span>作者: {{ post.author.username }}</span>
                <span>所属板块: {{ post.board_name }}</span>
                <span>阅读数: {{ post.read_count }}</span>
                <span>评论数: 0</span>
            </p>
            <article class="post-content" id="post-content" data-id ="{{ post.id }}">
                {{ post.content | safe }}
            </article>
        </div>
        <div class="comment-group">
            <h3>评论列表</h3>
            <ul class="comment-list-group">
                {% for comment in post.comments %}
                    <div class="avatar-group">
                        <img src="{{ comment.author.avatar or static('common/images/logo.png') }}" alt="">
                    </div>
                    <div class="comment-content">
                    <p class="author-info">
                        <span>{{ comment.author.username }}</span>
                        <span>{{ comment.create_time }}</span>
                    </p>
                    <p class="comment-txt">
                        <li>{{ comment.content | safe }}</li>
                    </p>
                    </div>
                {% endfor %}
            </ul>
        </div>
        <div class="add-comment-group">
            <h3 style="margin-bottom: 10px">发表评论</h3>
        <script id="editor" type="text/plain" style="height:100px;"></script>
            <div  class='comment-btn-group'>
            <button class="btn btn-primary" id='comment-btn'>发表评论</button>
            </div>
        </div>
    </div>
    <div class="sm-container">

    </div>
{% endblock %}

templates/front/front_signin.html
{% from 'common/_macros.html' import static %}
{% extends 'front/front_base.html' %}

{% block title %}
登录
{% endblock %}
{% block head %}
    <script src="{{ static('front/js/front_signin.js') }}"></script>

{% endblock %}
{% block h2_block %}
登录
{% endblock %}
{% block sign_box %}
    <div class="form-group">
       <input type="text" class="form-control" name="telephone"
        placeholder="手机号码">
    </div>
    <div class="form-group">
       <input type="password" class="form-control" name="password"
        placeholder="密码">
    </div>
    <div class="checkbox">
    <label>
        <input type="checkbox" name="remember" value="1">记住我
    </label>
    </div>
    <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn">
                    立即登录
                </button>
    </div>

    <div class="form-group">
        <a href="{{ url_for('front.signup') }}" class="signup-link">没有账号?立即注册</a>
        <a href="#" class="restpwd-link" style="float: right">找回密码</a>
    </div>
{% endblock %}

templates/front/front_signup.html
{% from 'common/_macros.html' import static %}
{% extends 'front/front_base.html' %}
{% block title %}
注册
{% endblock %}
{% block head %}
    <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.js"></script>
    <script src="{{ static('front/js/front_signup.js') }}"></script>
{% endblock %}
{% block h2_block %}
    注册账号
{% endblock %}
{% block sign_box %}
            <div class="form-group">
                <div class="input-group">
                <input type="text" class="form-control" name="telephone"
                placeholder="手机号码">
                    <span class="input-group-btn">
                        <button class="btn btn-default" id="sms-captcha-btn">发送验证码</button>
                    </span>
                </div>
            </div>
            <div class="form-group">
               <input type="text" class="form-control" name="sms_captcha"
                placeholder="短信验证码">
            </div>
            <div class="form-group">
               <input type="text" class="form-control" name="username"
                placeholder="用户名">
            </div>
            <div class="form-group">
               <input type="password" class="form-control" name="password1"
                placeholder="密码">
            </div>
            <div class="form-group">
               <input type="password" class="form-control" name="password2"
                placeholder="确认密码">
            </div>
            <div class="form-group">
                <div class="input-group">
                <input type="text" class="form-control" name="graph_captcha"
                placeholder="图形验证码">
                    <span class="input-group-addon captcha-addon">
                        <img id='captcha-img' class="captcha-img" src="{{ url_for('common.graph_captcha') }}" alt="">
                    </span>
                </div>
                </div>

                <div class="form-group">
                <button class="btn btn-warning btn-block" id="submit-btn">
                    立即登录
                </button>
            </div>
{% endblock %}

templates/front/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
测试页面
<br>
<br>
<br>
<br>
<br>
<a href="{{ url_for('front.signup') }}">注册</a>
<a href="{{ url_for('front.signin') }}">登录</a>
</body>
</html>