apps/cms/models.py
# -*- coding: UTF-8 -*-

from exts import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash


class CMSPermission(object):
    # 255的二级制方式来表示 1111 1111
    ALL_PERMISSION = 0b11111111
    # 1、访问者权限
    VISITOR = 0b00000001
    # 2、管理帖子的权限
    POSTER = 0b00000010
    # 3、管理评论的权限
    COMMENTER = 0b00000100
    # 4、管理板块的权限
    BOARDER = 0b00001000
    # 5、管理前台用户的权限
    FRONTER = 0b00010000
    # 6、管理后台用户的权限
    CMSUSER = 0b00100000
    # 7、管理后台管理员的权限
    ADMINER = 0b01000000


cms_role_user = db.Table(
    'cms_role_user',
    db.Column('cms_role_id', db.Integer, db.ForeignKey('cms_role.id'), primary_key=True),
    db.Column('cms_user_id', db.Integer, db.ForeignKey('cms_user.id'), primary_key=True)
)


class CMSRole(db.Model):
    __tablename__ = 'cms_role'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50), nullable=False)
    desc = db.Column(db.String(200), nullable=True)
    create_time = db.Column(db.DateTime, default=datetime.now)
    permissions = db.Column(db.Integer, default=CMSPermission.VISITOR)
    users = db.relationship('CMSUser', secondary=cms_role_user, backref='roles')


class CMSUser(db.Model):
    __tablename__ = 'cms_user'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(50), nullable=False)
    # 前边加了_的字段，代表这个字段是受保护的，方法外不能直接访问
    _password = db.Column(db.String(200), nullable=False)
    email = db.Column(db.String(50), nullable=False, unique=True)
    join_time = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, username, password, email):
        self.username = username
        self.password = password
        self.email = email


    # 使用property，将类方法定义成属性
    @property
    def password(self):
        return self._password

    # 对存入的密码进行加密，对外的字段命名叫做password，对内使用的字段名叫做_password
    @password.setter
    def password(self, raw_password):
        self._password = generate_password_hash(raw_password)

    def check_password(self, raw_password):
        result = check_password_hash(self.password, raw_password)
        return result

    @property
    def permissions(self):
        if not self.roles:
            return 0
        all_permissions = 0
        for role in self.roles:
            permissions = role.permissions
            all_permissions |= role.permissions
        return all_permissions

    def has_permission(self, permission):
        # all_permissions = self.permissions
        # result = all_permissions & permission == permission
        # return result
        return self.permissions & permission == permission

    @property
    def is_developer(self):
        return self.has_permission(CMSPermission.ALL_PERMISSION)

apps/cms/forms.py
# -*- coding: UTF-8 -*-


from wtforms import Form, StringField, IntegerField, ValidationError
from wtforms.validators import Email, InputRequired, Length, EqualTo
from ..forms import BaseForm
from utils import lyccache
from flask import g
from exts import db
from .models import CMSUser


class LoginForm(BaseForm):
    email = StringField(validators=[Email(message='请输入正确的有邮箱格式'),
                                    InputRequired(message='请输入邮箱')])
    password = StringField(validators=[Length(6, 20, message='请输入正确的密码')])
    remember = IntegerField()


class ResetPassworldForm(BaseForm):
    oldpwd = StringField(validators=[Length(6, 20, message='请输入正确的密码')])
    newpwd = StringField(validators=[Length(6, 20, message='请输入正确的密码')])
    newpwd2 = StringField(validators=[EqualTo('newpwd', message='两次输入的密码不一致')])


class ResetEmailForm(BaseForm):
    email = StringField(validators=[Email(message='请输入正确的有效格式')])
    captcha = StringField(validators=[Length(6, 6, message='请输入正确长度的验证码')])

    # 从memcached中获取邮箱和验证码，判断验证码是否正确
    def validate_captcha(self, field):
        print('field is %s' % field)
        # 这个地方的filed就代表的是captcha
        captcha = field.data
        email = self.email.data
        captcha_cacha = lyccache.get(email)
        print('email is %s' % email)
        print('captcha is %s' % captcha)
        print('captcha_cacha is %s' % captcha_cacha)
        if not captcha_cacha or captcha.lower() != captcha_cacha.lower():
            raise ValidationError('邮箱验证码错误！')

    # 验证邮箱是不是和原来的相同, 还需要判断更改的邮箱不能被其他人使用过
    def validate_email(self, field):
        email = field.data
        # 这个g.cms_user 是在钩子函数中定义的
        user = g.cms_user
        if user.email == email:
            raise ValidationError('不能和原来的邮箱相同！')
        if db.session.query(CMSUser).filter_by(email=email).first():
            raise ValidationError('该邮箱已注册！')


class AddBannerForm(BaseForm):
    name = StringField(validators=[InputRequired(message='请输入轮播图名称')])
    image_url = StringField(validators=[InputRequired(message='请输入轮播图的url')])
    link_url = StringField(validators=[InputRequired(message='请输入轮播图的跳转url')])
    priority = IntegerField(validators=[InputRequired(message='请输入轮播图的优先级')])


class UpdateBannerForm(AddBannerForm):
    banner_id = IntegerField(validators=[InputRequired(message='请输入轮播图的ID')])


class AddBoardForm(BaseForm):
    name = StringField(validators=[InputRequired(message='请输入板块名称')])


class UpdateBoardForm(AddBoardForm):
    board_id = IntegerField(validators=[InputRequired(message='请输入板块ID')])

apps/cms/__init__.py
# -*- coding: UTF-8 -*-

# 在主app中导入cms的时候，会执行这个init文件

from .views import bp
# 注意这里要导入hooks才能被执行
import apps.cms.hooks

apps/cms/views.py
# -*- coding: UTF-8 -*-

from flask import Blueprint, render_template, views, request, session, redirect,\
    url_for, g, jsonify
from .forms import LoginForm, ResetPassworldForm, ResetEmailForm, AddBannerForm,\
    UpdateBannerForm, AddBoardForm, UpdateBoardForm
from .models import CMSUser, CMSPermission
from .decorates import login_required, permission_required
import config
from exts import db, mail
from flask_mail import Message
from utils import restful, lyccache
import string
import random
from ..models import BannerModel, BorderModel


bp = Blueprint('cms', __name__, url_prefix='/cms')


@bp.route('/aboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def add_board():
    form = AddBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board = BorderModel(name=name)
        db.session.add(board)
        db.session.commit()
        return restful.success()
    else:
        return restful.paramerror(message=form.get_error())


@bp.route('/uboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def update_board():
    form = UpdateBoardForm(request.form)
    if form.validate():
        board_id = form.board_id.data
        name = form.name.data
        print(name)
        board = BorderModel.query.get(board_id)
        if board:
            board.name = name
            db.session.commit()
            return restful.success()
        else:
            return restful.paramerror(message='没有这个板块')
    else:
        return restful.paramerror(form.get_error())


@bp.route('/dboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def delete_board():
    board_id = request.form.get('board_id')
    print(board_id)
    if not board_id:
        return restful.paramerror(message='请输入板块ID')
    board = BorderModel.query.get(board_id)
    if board:
        db.session.delete(board)
        db.session.commit()
        print('123132')
        return restful.success()
    else:
        return restful.paramerror(message='没有这个板块')


@bp.route('/dbanner/', methods=['GET', 'POST'])
@login_required
def delete_banner():
    banner_id = request.form.get('banner_id')
    if not banner_id:
        return restful.paramerror(message='请传入轮播图ID')
    banner = BannerModel.query.get(banner_id)
    if not banner:
        return restful.paramerror(message='没有这个轮播图')
    db.session.delete(banner)
    db.session.commit()
    return restful.success()


@bp.route('/ubanner/', methods=['GET', 'POST'])
@login_required
def update_banner():
    form = UpdateBannerForm(request.form)
    if form.validate():
        banner_id = form.banner_id.data
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel.query.get(banner_id)
        if banner:
            banner.name = name
            banner.image_url = image_url
            banner.link_url = link_url
            banner.priority = priority
            db.session.commit()
            return restful.success()
        else:
            return restful.paramerror(message='没有这个轮播图')
    else:
        return restful.paramerror(message=form.get_error())


@bp.route('/abanner/', methods=['GET', 'POST'])
# @bp.route('/abanner/')
@login_required
def add_banner():
    form = AddBannerForm(request.form)
    if form.validate():
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel(name=name, image_url=image_url, link_url=link_url, priority=priority)
        db.session.add(banner)
        db.session.commit()
        return restful.success()
    else:
        return restful.paramerror(message=form.get_error())


class ResetEmailView(views.MethodView):
    decorators = [login_required]
    def get(self):
        return render_template('cms/cms_resetemail.html')
    def post(self):
        form = ResetEmailForm(request.form)
        if form.validate():
            email = form.email.data
            g.cms_user.email = email
            db.session.commit()
            return restful.success()
        else:
            return restful.paramerror(form.get_error())


@bp.route('/email_captcha/')
def email_captcha():
    # 通过查询字符串的方式将邮箱传递进去
    # /email_captcha/?email=xxx@qq.com
    email = request.args.get('email')
    if not email:
        return restful.paramerror('请传递邮箱参数!')
    # 生成验证码
    source = list(string.ascii_letters)
    # source.extend(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'])
    source.extend(map(lambda x: str(x), range(0, 10)))
    # 随机采样
    captcha = "".join(random.sample(source, 6))
    # 发送验证码
    message = Message(subject='验证码', recipients=[email], body='您的验证码是%s' % captcha)
    try:
        mail.send(message)
    except:
        return restful.servererror()
    lyccache.set(email, captcha)
    return restful.success(message='邮件发送成功')


# 测试邮件发送
@bp.route('/email/')
def send_email():
    print(db.session.query(CMSUser).filter_by(email='xuptwgl@163.com').first().email)
    print(type((db.session.query(CMSUser).filter_by(email='xuptwgl@163.com').first())))
    return "%s" % db.session.query(CMSUser).filter_by(email='xuptwgl@163.com').first().email
    message = Message(subject='test邮件发送', recipients=['xuptwgl@163.com'], body='测试1')
    mail.send(message)
    return '邮件发送成功！！！'


@bp.route('/')
@login_required
def index():
    return render_template('cms/cms_index.html')

@bp.route('/logout/')
@login_required
def logout():
    # session.clear()
    del session[config.CMS_USER_ID]
    return redirect(url_for('cms.login'))

@bp.route('/profile/')
@login_required
def profile():
    return render_template('cms/cms_profile.html')


class ResetPwdView(views.MethodView):
    # 在类视图中使用装饰器
    decorators = [login_required]
    def get(self):
        return render_template('cms/cms_resetpwd.html')
    def post(self):
        form = ResetPassworldForm(request.form)
        if form.validate():
            user_id = session.get(config.CMS_USER_ID)
            user = CMSUser.query.get(user_id)
            old_passwd = form.oldpwd.data
            print(old_passwd)
            if user.check_password(old_passwd):
                new_passwd = form.newpwds
                print(user)
                print(user.password)
                print(new_passwd.data)
                # 注意这里需要.data
                user.password = new_passwd.data
                db.session.commit()
                # return '修改成功'
                # return jsonify({
                #     'code': 200,
                #     'message': ''
                # })
                return restful.success()

            else:
                print('输入的原密码错误')
                # return '输入的原密码错误'
                # return jsonify({
                #     'code': 400,
                #     'message': '原密码输入错误'
                # })
                return restful.paramerror(message='原密码输入错误')
                # return restful.paramerror()
        else:
            print(form.errors)
            # return jsonify({
            #     'code': 400,
            #     'message': form.get_error()
            # })
            return restful.paramerror(form.get_error())
            # return restful.paramerror()


# 先判断登录，再判断权限
# bp.route('/posts/') 这个要写在上边。为什么？？？
"""
多重装饰器，在调用的时候从下往上，在执行内函数的时候从上往下
"""
@bp.route('/posts/')
@login_required
@permission_required(CMSPermission.POSTER)
def posts():
    return render_template('cms/cms_posts.html')


@bp.route('/banners')
@login_required
def banners():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    return render_template('cms/cms_banners.html', banners=banners)


@bp.route('/comments/')
@login_required
@permission_required(CMSPermission.COMMENTER)
def comments():
    return render_template('cms/cms_comments.html')


@bp.route('/boards/')
@login_required
@permission_required(CMSPermission.BOARDER)
def boards():
    board_models = BorderModel.query.all()
    context = {
        'boards': board_models
    }
    return render_template('cms/cms_boards.html', **context)


@bp.route('/fusers/')
@login_required
@permission_required(CMSPermission.FRONTER)
def fusers():
    return render_template('cms/cms_fusers.html')

@bp.route('/cusers/')
@login_required
@permission_required(CMSPermission.ADMINER)
def cusers():
    return render_template('cms/cms_cusers.html')


@login_required
@permission_required(CMSPermission.ALL_PERMISSION)
@bp.route('/croles/')
def croles():
    return render_template('cms/cms_croles.html')


# 这里使用类视图
class LoginView(views.MethodView):

    def get(self, message=None):
        return render_template('cms/cms_login.html', message=message)

    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = CMSUser.query.filter_by(email=email).first()
            if user and user.check_password(password):
                # 这里我们定义一个常量CMS_USER_ID,这样的话在使用的时候就不需要去写字符串，
                # 避免出错和与其他名字冲突
                session[config.CMS_USER_ID] = user.id
                # 如果选择了记住我，则长时间保存session
                if remember:
                    # 设置为True，默认为31天过期
                    session.permanent = True
                # 注意这里使用了蓝图，所以这里使用url反转的时候需要加蓝图.xx
                return redirect(url_for('cms.index'))
            else:
                return self.get(message='登录失败，邮箱或者密码错误')
                # return restful.paramerror(message='登录失败，邮箱或者密码错误')
                # return restful.paramerror()

        else:
            print(form.errors)
            # 避免代码冗余，使用self.get()
            return self.get(message='%s' % form.get_error())


bp.add_url_rule('/login/', view_func=LoginView.as_view('login'))

templates/cms/cms_banners.html
{% extends 'cms/cms_base.html' %}
{% from "common/_macros.html" import static %}

{% block title %}
    轮播图管理
{% endblock %}

{% block head %}
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/moxie.js"></script>
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/plupload.dev.js"></script>
    <script src="https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.js"></script>
    <script src="{{ url_for('static',filename='common/zlqiniu.js') }}"></script>
    <script src="{{ static('cms/js/banners.js') }}"></script>
    <style>
    .top-box button{
        float: right;

    }
    </style>
{% endblock %}

{% block page_title %}
{{ self.title() }}
{% endblock %}

{% block main_content %}
<div class="top-box">
    <button class="btn btn-warning" type="button" -class="btn btn-primary btn-lg" data-toggle="modal"
            data-target="#banner-dialog">添加轮播图</button>
</div>
    <table class="table table-bordered">
    <thead>
    <tr>
        <th>名称</th>
        <th>图片链接</th>
        <th>跳转链接</th>
        <th>优先级</th>
        <th>创建时间</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
        {% for banner in banners %}
            <tr data-name="{{ banner.name }}" data-image="{{ banner.image_url }}"
            data-link="{{ banner.link_url }}" data-priority="{{ banner.priority }}"
            data-id="{{ banner.id }}">
            <td>{{ banner.name }}</td>
            <td>
                <a href="{{ banner.image_url }}" target="_blank">{{ banner.image_url }}</a>
            </td>
            <td>
                <a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a>
            </td>
            <td>{{ banner.priority }}</td>
            <td>{{ banner.create_time }}</td>
            <td>
                <button class="btn btn-default btn-xs edit-banner">编辑</button>
                <button class="btn btn-danger btn-xs delete-banner">删除</button>
            </td>
            </tr>
        {% endfor %}

    </tbody>
    </table>
<!-- Modal -->
<div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">轮播图</h4>
      </div>
      <div class="modal-body">
        <div class="form-horizontal">
            <div class="form-group">
                <label class="col-lg-2 control-label">名称:</label>
                <div class="col-lg-10">
                    <input type="text" class="form-control" name="name"
                    placeholder="轮播图名称">
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 control-label">图片:</label>
                <div class="col-lg-7">
                    <input type="text" class="form-control" name="image-url"
                    placeholder="轮播图图片">
                </div>
                <button class="btn btn-info col-lg-2" id="upload-btn">添加图片</button>
            </div>
            <div class="form-group">
                 <label class="col-lg-2 control-label">跳转:</label>
                <div class="col-lg-10">
                    <input type="text" class="form-control" name="link-url"
                    placeholder="轮播图URL">
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 control-label">权重:</label>
                <div class="col-lg-10">
                    <input type="number" class="form-control" name="priority"
                    placeholder="优先级">
                </div>
            </div>
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary" id="save-banner-btn">保存</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/cms/cms_base.html
{% from "common/_macros.html" import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% include 'common/_heads.html' %}
    <link rel="stylesheet" href="{{ static('cms/css/base.css') }}">
    <script src="{{ static('cms/js/base.js') }}"></script>
    <script src="{{ static("common/zlajax.js") }}"></script>
    <link rel="stylesheet" href="{{ static("common/sweetalert/sweetalert.css") }}">

    {% block head %}{% endblock %}
</head>
<body>
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">知了课堂论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">{{ g.cms_user.username }}<span></span></a></li>
            <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="查找...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for("cms.resetpwd") }}">修改密码</a></li>
                        <li><a href="{{ url_for("cms.resetemail") }}">修改邮箱</a></li>
                    </ul>
                </li>
{#                先设置一个变量 cms_user #}
                {% set cms_user = g.cms_user %}
                <li class="nav-group banners-manage"><a href={{ url_for('cms.banners') }}>轮播图管理</a></li>
                {% if cms_user.has_permission(CMSPermission.POSTER) %}
                    <li class="nav-group post-manage"><a href={{ url_for('cms.posts') }}>帖子管理</a></li>
                {% endif %}
                {% if cms_user.has_permission(CMSPermission.COMMENTER) %}
                    <li class="comments-manage"><a href={{ url_for('cms.comments') }}>评论管理</a></li>
                {% endif %}
                {% if cms_user.has_permission(CMSPermission.BOARDER) %}
                    <li class="board-manage"><a href={{ url_for('cms.boards') }}>板块管理</a></li>
                {% endif %}
                {% if cms_user.has_permission(CMSPermission.FRONTER) %}
                    <li class="nav-group user-manage"><a href={{ url_for('cms.fusers') }}>前台用户管理</a></li>
                {% endif %}
{#                <li class="role-manage"><a href="#">组管理</a></li>#}
                {% if cms_user.has_permission(CMSPermission.CMSUSER) %}
                    <li class="nav-group cmsuser-manage"><a href={{ url_for('cms.cusers') }}>CMS用户管理</a></li>
                {% endif %}
                {% if cms_user.is_developer %}
                     <li class="cmsrole-manage"><a href={{ url_for('cms.croles') }}>CMS组管理</a></li>
                {% endif %}
            </ul>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}{% endblock %}
            </div>
          </div>
      </div>
    </div>
</body>
</html>

templates/cms/cms_boards.html
{%  extends 'cms/cms_base.html' %}

{% block title %}
    板块管理
{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/boards.js') }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
<div class="top-box">
<button class="btn btn-warning" style="float: right" id="add-board-btn">
    添加新板块
</button>
</div>
<table class="table table-bordered">
<thead>
<tr>
    <th>板块名称</th>
    <th>帖子数量</th>
    <th>创建时间</th>
    <th>操作</th>
</tr>
</thead>
<tbody>
{% for board in boards %}
    <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
{#    {{ board.id }}#}
    <td>{{ board.name }}</td>
    <td>0</td>
    <td>{{ board.create_time }}</td>
    <td>
        <button class="btn btn-default btn-xs edit-board-btn">编辑</button>
        <button class="btn btn-danger btn-xs delete-board-btn">删除</button>
    </td>
    </tr>
{% endfor %}

</tbody>
</table>
{% endblock %}

templates/cms/cms_comments.html
{%  extends 'cms/cms_base.html' %}

{% block title %}
    评论管理
{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是评论管理页面
{% endblock %}

templates/cms/cms_croles.html
{%  extends 'cms/cms_base.html' %}

{% block title %}
    角色管理
{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是角色管理页面
{% endblock %}

templates/cms/cms_cusers.html
{%  extends 'cms/cms_base.html' %}

{% block title %}
    cms用户管理
{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是cms用户管理页面
{% endblock %}

templates/cms/cms_fusers.html
{%  extends 'cms/cms_base.html' %}

{% block title %}
    前台用户管理
{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是前台用户管理页面
{% endblock %}

templates/cms/cms_index.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    lyc课堂CMS管理系统
{% endblock %}

{% block page_title %}
    欢迎来到lyc课堂CMS管理系统
{% endblock %}


templates/cms/cms_login.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>登录-LYC论坛CMS管理系统</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{{ url_for('static',filename='cms/css/signin.css') }}" rel="stylesheet">
  </head>

  <body>

    <div class="container">
      <form class="form-signin" method="post">
        <h2 class="form-signin-heading">请登录</h2>
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <label for="inputEmail" class="sr-only">邮箱：</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="邮箱" name="email" required autofocus>
        <label for="inputPassword" class="sr-only">密码：</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="密码" name="password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="1" name="remember">记住我
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">立即登录</button>
      </form>
        {% if message %}
            <p style="text-align: center;" class="text-danger">{{ message }}</p>
        {% endif %}
    </div> <!-- /container -->
  </body>
</html>

templates/cms/cms_posts.html
{%  extends 'cms/cms_base.html' %}

{% block title %}
    评论管理
{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是评论管理页面
{% endblock %}